{{- if .Values.vaultSecrets.artifactStorage }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argo-artifacts-creds
spec:
  type: Opaque
  {{- if .Values.vaultSecrets.artifactStorage.s3 }}
  path: {{ .Values.vaultSecrets.artifactStorage.s3 }}
  keys:
  - aws_access_key_id
  - aws_secret_access_key
  {{- else if .Values.vaultSecrets.artifactStorage.genericArtifactory }}
  path: {{ .Values.vaultSecrets.artifactStorage.genericArtifactory }}
  keys:
  - username
  - token
  {{- end }}
{{- end }}