{{- if .Values.vaultSecrets.corpArtifactory }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: artifactory-creds
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.corpArtifactory }}
  keys:
  - username
  - token
{{- end }}