{{- if .Values.vaultSecrets.cloudArtifactory }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: image-push-creds
spec:
  type: opaque
  path: {{ .Values.vaultSecrets.cloudArtifactory }}
  keys:
  - username
  - token
{{- end }}