{{- if .Values.vaultSecrets.jenkins }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: jenkins-creds
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.jenkins }}
  keys:
  - api_token
  - user
{{- end }}