{{- if (.Values.skms).enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: skms-api-user
spec:
  type: Opaque
  path: {{ .Values.vaultSecrets.skmsApiUser }}
  keys:
  - username
  - passkey
{{- end }}
