{{- if .Values.vaultSecrets.slack }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: slack-secret
spec:
  type: opaque
  path: {{ .Values.vaultSecrets.slack }}
  keys:
  - webhook_url
{{- end }}
